/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TelaPrincipal.java
 *
 * Created on 17/01/2014, 10:48:26
 */
package jhospital.view;

import javax.swing.JOptionPane;
import jhospital.view.cadastro.CadastroDeEnfermeiroView;
import jhospital.view.cadastro.CadastroDeMedicoView;
import jhospital.view.cadastro.CadastroDePacienteView;
import jhospital.view.cadastro.CadastroDeVisitanteView;
import jhospital.view.consulta.ConsultaDeEnfermeiroView;
import jhospital.view.consulta.ConsultaDeMedicoView;
import jhospital.view.consulta.ConsultaDePacienteView;
import jhospital.view.consulta.ConsultaDeVisitanteView;

/**
 *
 * @author GNascimento
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /** Creates new form TelaPrincipal */
    public TelaPrincipal() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPanePrincipal = new javax.swing.JTabbedPane();
        menuPrincipal = new javax.swing.JMenuBar();
        menuArquivo = new javax.swing.JMenu();
        menuItemSair = new javax.swing.JMenuItem();
        menuCadastro = new javax.swing.JMenu();
        menuItemCadastroDePaciente = new javax.swing.JMenuItem();
        menuItemCadastroDeVisitante = new javax.swing.JMenuItem();
        menuItemCadastroDeMedico = new javax.swing.JMenuItem();
        menuItemCadastroDeEnfermeiro = new javax.swing.JMenuItem();
        menuConsulta = new javax.swing.JMenu();
        menuItemConsultaDePaciente = new javax.swing.JMenuItem();
        menuItemConsultaDeVisitante = new javax.swing.JMenuItem();
        menuItemConsultaDeMedico = new javax.swing.JMenuItem();
        menuItemConsultaDeEnfermeiro = new javax.swing.JMenuItem();
        menuAjuda = new javax.swing.JMenu();
        menuItemSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JHospital");
        setName("telaPrincipal"); // NOI18N

        menuArquivo.setText("Arquivo");

        menuItemSair.setText("Sair");
        menuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSairActionPerformed(evt);
            }
        });
        menuArquivo.add(menuItemSair);

        menuPrincipal.add(menuArquivo);

        menuCadastro.setText("Cadastro");

        menuItemCadastroDePaciente.setText("Cadastro de Paciente");
        menuItemCadastroDePaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCadastroDePacienteActionPerformed(evt);
            }
        });
        menuCadastro.add(menuItemCadastroDePaciente);

        menuItemCadastroDeVisitante.setText("Cadastro de Visitante");
        menuItemCadastroDeVisitante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCadastroDeVisitanteActionPerformed(evt);
            }
        });
        menuCadastro.add(menuItemCadastroDeVisitante);

        menuItemCadastroDeMedico.setText("Cadastro de Médico ");
        menuItemCadastroDeMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCadastroDeMedicoActionPerformed(evt);
            }
        });
        menuCadastro.add(menuItemCadastroDeMedico);

        menuItemCadastroDeEnfermeiro.setText("Cadastro de Enfermeiro");
        menuItemCadastroDeEnfermeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCadastroDeEnfermeiroActionPerformed(evt);
            }
        });
        menuCadastro.add(menuItemCadastroDeEnfermeiro);

        menuPrincipal.add(menuCadastro);

        menuConsulta.setText("Consulta");

        menuItemConsultaDePaciente.setText("Consulta de Paciente");
        menuItemConsultaDePaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemConsultaDePacienteActionPerformed(evt);
            }
        });
        menuConsulta.add(menuItemConsultaDePaciente);

        menuItemConsultaDeVisitante.setText("Consulta de Visitante");
        menuItemConsultaDeVisitante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemConsultaDeVisitanteActionPerformed(evt);
            }
        });
        menuConsulta.add(menuItemConsultaDeVisitante);

        menuItemConsultaDeMedico.setText("Consulta de Médico");
        menuItemConsultaDeMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemConsultaDeMedicoActionPerformed(evt);
            }
        });
        menuConsulta.add(menuItemConsultaDeMedico);

        menuItemConsultaDeEnfermeiro.setText("Consulta de Enfermeiro");
        menuItemConsultaDeEnfermeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemConsultaDeEnfermeiroActionPerformed(evt);
            }
        });
        menuConsulta.add(menuItemConsultaDeEnfermeiro);

        menuPrincipal.add(menuConsulta);

        menuAjuda.setText("Ajuda");

        menuItemSobre.setText("Sobre");
        menuItemSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSobreActionPerformed(evt);
            }
        });
        menuAjuda.add(menuItemSobre);

        menuPrincipal.add(menuAjuda);

        setJMenuBar(menuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tabbedPanePrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 693, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tabbedPanePrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void menuItemCadastroDePacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCadastroDePacienteActionPerformed
        tabbedPanePrincipal.add("Cadastro de Paciente",
                new CadastroDePacienteView(tabbedPanePrincipal));
        tabbedPanePrincipal.revalidate();
        tabbedPanePrincipal.repaint();
}//GEN-LAST:event_menuItemCadastroDePacienteActionPerformed

private void menuItemCadastroDeVisitanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCadastroDeVisitanteActionPerformed
         tabbedPanePrincipal.add("Cadastro de Visitante",
                new CadastroDeVisitanteView(tabbedPanePrincipal));
        tabbedPanePrincipal.revalidate();
        tabbedPanePrincipal.repaint();
}//GEN-LAST:event_menuItemCadastroDeVisitanteActionPerformed

private void menuItemCadastroDeMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCadastroDeMedicoActionPerformed
        tabbedPanePrincipal.add("Cadastro de Médico",
                new CadastroDeMedicoView(tabbedPanePrincipal));
        tabbedPanePrincipal.revalidate();
        tabbedPanePrincipal.repaint();
}//GEN-LAST:event_menuItemCadastroDeMedicoActionPerformed

private void menuItemCadastroDeEnfermeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCadastroDeEnfermeiroActionPerformed
        tabbedPanePrincipal.add("Cadastro de Enfermeiro",
                new CadastroDeEnfermeiroView(tabbedPanePrincipal));
        tabbedPanePrincipal.revalidate();
        tabbedPanePrincipal.repaint();
}//GEN-LAST:event_menuItemCadastroDeEnfermeiroActionPerformed

private void menuItemConsultaDePacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemConsultaDePacienteActionPerformed
        tabbedPanePrincipal.add("Consulta de Paciente",
                new ConsultaDePacienteView(tabbedPanePrincipal));
        tabbedPanePrincipal.revalidate();
        tabbedPanePrincipal.repaint();
}//GEN-LAST:event_menuItemConsultaDePacienteActionPerformed

private void menuItemConsultaDeVisitanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemConsultaDeVisitanteActionPerformed
        tabbedPanePrincipal.add("Consulta de Visitante",
                new ConsultaDeVisitanteView(tabbedPanePrincipal));
        tabbedPanePrincipal.revalidate();
        tabbedPanePrincipal.repaint();
}//GEN-LAST:event_menuItemConsultaDeVisitanteActionPerformed

private void menuItemConsultaDeMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemConsultaDeMedicoActionPerformed
        tabbedPanePrincipal.add("Consulta de Médico",
                new ConsultaDeMedicoView(tabbedPanePrincipal));
        tabbedPanePrincipal.revalidate();
        tabbedPanePrincipal.repaint();
}//GEN-LAST:event_menuItemConsultaDeMedicoActionPerformed

private void menuItemConsultaDeEnfermeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemConsultaDeEnfermeiroActionPerformed
        tabbedPanePrincipal.add("Consulta de Enfermeiro",
                new ConsultaDeEnfermeiroView(tabbedPanePrincipal));
        tabbedPanePrincipal.revalidate();
        tabbedPanePrincipal.repaint();
}//GEN-LAST:event_menuItemConsultaDeEnfermeiroActionPerformed

private void menuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSairActionPerformed
    if (JOptionPane.showConfirmDialog(this,
            "Deseja mesmo fechar o sistema?", "Confirmação",
            JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
        System.exit(0);
    }
}//GEN-LAST:event_menuItemSairActionPerformed

private void menuItemSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSobreActionPerformed
    JOptionPane.showMessageDialog(this,
            "JHospital\n\nVersão 1.0\nCopyright Nailton Silva ",
            "Sobre", JOptionPane.INFORMATION_MESSAGE);
}//GEN-LAST:event_menuItemSobreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu menuAjuda;
    private javax.swing.JMenu menuArquivo;
    private javax.swing.JMenu menuCadastro;
    private javax.swing.JMenu menuConsulta;
    private javax.swing.JMenuItem menuItemCadastroDeEnfermeiro;
    private javax.swing.JMenuItem menuItemCadastroDeMedico;
    private javax.swing.JMenuItem menuItemCadastroDePaciente;
    private javax.swing.JMenuItem menuItemCadastroDeVisitante;
    private javax.swing.JMenuItem menuItemConsultaDeEnfermeiro;
    private javax.swing.JMenuItem menuItemConsultaDeMedico;
    private javax.swing.JMenuItem menuItemConsultaDePaciente;
    private javax.swing.JMenuItem menuItemConsultaDeVisitante;
    private javax.swing.JMenuItem menuItemSair;
    private javax.swing.JMenuItem menuItemSobre;
    private javax.swing.JMenuBar menuPrincipal;
    private javax.swing.JTabbedPane tabbedPanePrincipal;
    // End of variables declaration//GEN-END:variables
}
