/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CadastroDeEnfermeiroView.java
 *
 * Created on 21/01/2014, 09:16:59
 */
package jhospital.view.cadastro;

import javax.swing.JOptionPane;
import javax.swing.JTabbedPane;
import jhospital.controller.EnfermeiroController;
import jhospital.model.Enfermeiro;


public class CadastroDeEnfermeiroView extends javax.swing.JPanel {

    private JTabbedPane tabbedPane;
    private Enfermeiro enfermeiro;
    
    public CadastroDeEnfermeiroView(JTabbedPane tabbedPane1) {
        this.tabbedPane = tabbedPane1;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelConsultaPaciente = new javax.swing.JLabel();
        SeparatorSuperior = new javax.swing.JSeparator();
        labelNome = new javax.swing.JLabel();
        textFieldNome = new javax.swing.JTextField();
        labelEndereco = new javax.swing.JLabel();
        textFieldEndereco = new javax.swing.JTextField();
        labelEmail = new javax.swing.JLabel();
        labelValorDaHora = new javax.swing.JLabel();
        textFieldValorDaHora = new javax.swing.JTextField();
        textFieldEmail = new javax.swing.JTextField();
        labelTelefone = new javax.swing.JLabel();
        labelHorasMensais = new javax.swing.JLabel();
        textFieldHorasMensais = new javax.swing.JTextField();
        textFieldTelefone = new javax.swing.JTextField();
        buttonSalvar = new javax.swing.JButton();
        buttonCancelar = new javax.swing.JButton();

        labelConsultaPaciente.setText("Cadastro de Enfermeiro");

        labelNome.setText("Nome Completo:");

        labelEndereco.setText("Endereço:");

        labelEmail.setText("Email:");

        labelValorDaHora.setText("Valor da Hora:");

        labelTelefone.setText("Telefone:");

        labelHorasMensais.setText("Horas Mensais:");

        buttonSalvar.setText("Salvar");
        buttonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSalvarActionPerformed(evt);
            }
        });

        buttonCancelar.setText("Cancelar");
        buttonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 569, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(SeparatorSuperior, javax.swing.GroupLayout.DEFAULT_SIZE, 549, Short.MAX_VALUE)
                        .addComponent(labelConsultaPaciente)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(labelNome)
                                .addComponent(labelEndereco)
                                .addComponent(labelEmail)
                                .addComponent(labelValorDaHora))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(textFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                                    .addComponent(labelTelefone)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(textFieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(textFieldEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
                                .addComponent(textFieldNome, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(textFieldValorDaHora, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelHorasMensais)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(textFieldHorasMensais, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(buttonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(27, 27, 27)
                                    .addComponent(buttonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addComponent(labelConsultaPaciente)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(SeparatorSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelNome)
                        .addComponent(textFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(16, 16, 16)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelEndereco)
                        .addComponent(textFieldEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelTelefone)
                        .addComponent(textFieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelEmail)
                        .addComponent(textFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelHorasMensais)
                        .addComponent(textFieldHorasMensais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelValorDaHora)
                        .addComponent(textFieldValorDaHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(65, 65, 65)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(buttonCancelar)
                        .addComponent(buttonSalvar))
                    .addContainerGap(22, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void preencherCampos(Integer idEnfermeiro) 
            throws Exception {
        EnfermeiroController ec = new EnfermeiroController();
        enfermeiro = ec.buscarEnfermeiroPeloId(idEnfermeiro);
        textFieldNome.setText(enfermeiro.getNome());
        textFieldEmail.setText(enfermeiro.getEmail());
        textFieldEndereco.setText(enfermeiro.getEndereco());
        textFieldTelefone.setText(enfermeiro.getTelefone());
        textFieldValorDaHora.setText(String
                .valueOf(enfermeiro.getValordashoras()));
        textFieldHorasMensais.setText(String
                .valueOf(enfermeiro.getHorasmensais()));
    }
    
        public CadastroDeEnfermeiroView(JTabbedPane tabbedPane1, 
            Integer idEnfermeiro) throws Exception {
        this.tabbedPane = tabbedPane1;
        initComponents();
        preencherCampos(idEnfermeiro);
    }
    
private void buttonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelarActionPerformed
    if (JOptionPane.showConfirmDialog(this,
            "Deseja mesmo fechar o cadastro de enfermeiro sem salvar?",
            "Confirmação", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
        tabbedPane.remove(this);
        tabbedPane.validate();
        tabbedPane.repaint();
    }
}//GEN-LAST:event_buttonCancelarActionPerformed

    private void buttonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSalvarActionPerformed
            if (textFieldNome != null && !textFieldNome.getText().equals("") &&
            textFieldEmail != null && !textFieldEmail.getText().equals("") &&
            textFieldEndereco != null && !textFieldEndereco.getText().equals("") &&
            textFieldValorDaHora != null && !textFieldValorDaHora.getText().equals("") &&
            textFieldHorasMensais != null && !textFieldHorasMensais.getText().equals("")
            ) {
        EnfermeiroController ec = new EnfermeiroController();
        try {
            if (enfermeiro != null && enfermeiro.getId() != null) {
                ec.alterar(enfermeiro.getId(),
                        textFieldNome.getText(),
                        textFieldEmail.getText(),
                        textFieldEndereco.getText(),
                        textFieldTelefone.getText(),
                        textFieldValorDaHora.getText(),
                        textFieldHorasMensais.getText());
                JOptionPane.showMessageDialog(this,
                        "Contato atualizado com sucesso!",
                        "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                tabbedPane.remove(this);
                tabbedPane.validate();
                tabbedPane.repaint();
            } else {
            ec.inserir(textFieldNome.getText().toUpperCase(),
                    textFieldEmail.getText().toLowerCase(),
                    textFieldEndereco.getText().toUpperCase(),
                    textFieldTelefone.getText(),
                    textFieldValorDaHora.getText(),
                    textFieldHorasMensais.getText());
            JOptionPane.showMessageDialog(this,
                    "Enfermeiro salvo com sucesso!",
                    "Sucesso", JOptionPane.INFORMATION_MESSAGE);
            limparDados();
            }
        }catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Não foi possível salvar Enfermeiro\n"
                    + e.getLocalizedMessage(),
                    "Erro", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "O nome, email, endereço, valor da hora e horas mensais do enfermeiro são campos obrigatórios!",
                    "Erro", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_buttonSalvarActionPerformed

    private void limparDados(){
    textFieldNome.setText("");
    textFieldEmail.setText("");
    textFieldEndereco.setText("");
    textFieldTelefone.setText("");
    textFieldValorDaHora.setText("");
    textFieldHorasMensais.setText("");
}
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator SeparatorSuperior;
    private javax.swing.JButton buttonCancelar;
    private javax.swing.JButton buttonSalvar;
    private javax.swing.JLabel labelConsultaPaciente;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelEndereco;
    private javax.swing.JLabel labelHorasMensais;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelTelefone;
    private javax.swing.JLabel labelValorDaHora;
    private javax.swing.JTextField textFieldEmail;
    private javax.swing.JTextField textFieldEndereco;
    private javax.swing.JTextField textFieldHorasMensais;
    private javax.swing.JTextField textFieldNome;
    private javax.swing.JTextField textFieldTelefone;
    private javax.swing.JTextField textFieldValorDaHora;
    // End of variables declaration//GEN-END:variables
}
