/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CadastroDeVisitanteView.java
 *
 * Created on 21/01/2014, 08:36:03
 */
package jhospital.view.cadastro;

import javax.swing.JOptionPane;
import javax.swing.JTabbedPane;
import jhospital.controller.VisitanteController;
import jhospital.model.Visitante;

/**
 *
 * @author GNascimento
 */
public class CadastroDeVisitanteView extends javax.swing.JPanel {

    private JTabbedPane tabbedPane;
    private Visitante visitante;
    
    public CadastroDeVisitanteView(JTabbedPane tabbedPane1) {
        this.tabbedPane = tabbedPane1;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelCadastroDeVisitante = new javax.swing.JLabel();
        separatorSuperior = new javax.swing.JSeparator();
        textFieldNome = new javax.swing.JTextField();
        labelNome = new javax.swing.JLabel();
        labelEndereco = new javax.swing.JLabel();
        textFieldEndereco = new javax.swing.JTextField();
        labelEmail = new javax.swing.JLabel();
        textFieldEmail = new javax.swing.JTextField();
        labelTelefone = new javax.swing.JLabel();
        textFieldTelefone = new javax.swing.JTextField();
        labelPaciente = new javax.swing.JLabel();
        textFieldPaciente = new javax.swing.JTextField();
        buttonSalvar = new javax.swing.JButton();
        buttonCancelar = new javax.swing.JButton();

        labelCadastroDeVisitante.setText("Cadastro de Visitante");

        labelNome.setText("Nome Completo:");

        labelEndereco.setText("Endereço:");

        labelEmail.setText("Email:");

        labelTelefone.setText("Telefone:");

        labelPaciente.setText("Paciente:");

        buttonSalvar.setText("Salvar");
        buttonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSalvarActionPerformed(evt);
            }
        });

        buttonCancelar.setText("Cancelar");
        buttonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 625, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(separatorSuperior, javax.swing.GroupLayout.DEFAULT_SIZE, 605, Short.MAX_VALUE)
                        .addComponent(labelCadastroDeVisitante)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(labelNome)
                                .addComponent(labelEndereco)
                                .addComponent(labelEmail)
                                .addComponent(labelPaciente))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(textFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                                    .addComponent(labelTelefone)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(textFieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(textFieldEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE)
                                .addComponent(textFieldNome, javax.swing.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(241, 241, 241)
                                    .addComponent(buttonSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                                    .addGap(53, 53, 53)
                                    .addComponent(buttonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(textFieldPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE))))
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addComponent(labelCadastroDeVisitante)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(separatorSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelNome)
                        .addComponent(textFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(16, 16, 16)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelEndereco)
                        .addComponent(textFieldEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelTelefone)
                        .addComponent(textFieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelEmail)
                        .addComponent(textFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelPaciente)
                        .addComponent(textFieldPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(65, 65, 65)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(buttonCancelar)
                        .addComponent(buttonSalvar))
                    .addContainerGap(22, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents
   
    private void preencherCampos(Integer idVisitante) throws Exception {
        VisitanteController vc = new VisitanteController();
        visitante = vc.buscarVisitantePeloId(idVisitante);
        textFieldNome.setText(visitante.getNome());
        textFieldEmail.setText(visitante.getEmail());
        textFieldEndereco.setText(visitante.getEndereco());
        textFieldTelefone.setText(visitante.getTelefone());
        textFieldPaciente.setText(visitante.getPaciente());
    }
    
    public CadastroDeVisitanteView(JTabbedPane tabbedPane1,
            Integer idVisitante) throws Exception {
        this.tabbedPane = tabbedPane1;
        initComponents();
        preencherCampos(idVisitante);
    }
private void buttonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelarActionPerformed
    if (JOptionPane.showConfirmDialog(this,
            "Deseja mesmo fechar o cadastro de visitante sem salvar?",
            "Confirmação", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
        tabbedPane.remove(this);
        tabbedPane.validate();
        tabbedPane.repaint();
    }// TODO add your handling code here:
}//GEN-LAST:event_buttonCancelarActionPerformed

    private void buttonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSalvarActionPerformed
        if (textFieldNome != null && !textFieldNome.getText().equals("") &&
            textFieldEmail != null && !textFieldEmail.getText().equals("") &&
            textFieldEndereco != null && !textFieldEndereco.getText().equals("") &&
            textFieldPaciente != null && !textFieldPaciente.getText().equals("")
            ) {
        VisitanteController vc = new VisitanteController();
            try {
            if (visitante != null && visitante.getId() != null) {
                vc.alterar(visitante.getId(),
                        textFieldNome.getText(),
                        textFieldEmail.getText(),
                        textFieldEndereco.getText(),
                        textFieldTelefone.getText(),
                        textFieldPaciente.getText());
                JOptionPane.showMessageDialog(this,
                        "Contato atualizado com sucesso!",
                        "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                tabbedPane.remove(this);
                tabbedPane.validate();
                tabbedPane.repaint();
            } else {
            vc.inserir(textFieldNome.getText().toUpperCase(),
                    textFieldEmail.getText().toLowerCase(),
                    textFieldEndereco.getText().toUpperCase(),
                    textFieldTelefone.getText(),
                    textFieldPaciente.getText().toUpperCase());
            JOptionPane.showMessageDialog(this,
                    "Visitante salvo com sucesso!",
                    "Sucesso", JOptionPane.INFORMATION_MESSAGE);
            limparDados();
            }
        }catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Não foi possível salvar Visitante\n"
                    + e.getLocalizedMessage(),
                    "Erro", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "O nome, email, endereço e paciente do visitante são campos obrigatórios!",
                    "Erro", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_buttonSalvarActionPerformed

    private void limparDados(){
    textFieldNome.setText("");
    textFieldEmail.setText("");
    textFieldEndereco.setText("");
    textFieldTelefone.setText("");
    textFieldPaciente.setText("");
}
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancelar;
    private javax.swing.JButton buttonSalvar;
    private javax.swing.JLabel labelCadastroDeVisitante;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelEndereco;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelPaciente;
    private javax.swing.JLabel labelTelefone;
    private javax.swing.JSeparator separatorSuperior;
    private javax.swing.JTextField textFieldEmail;
    private javax.swing.JTextField textFieldEndereco;
    private javax.swing.JTextField textFieldNome;
    private javax.swing.JTextField textFieldPaciente;
    private javax.swing.JTextField textFieldTelefone;
    // End of variables declaration//GEN-END:variables
}
