/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CadastroDePacienteView.java
 *
 * Created on 17/01/2014, 16:14:23
 */
package jhospital.view.cadastro;

import javax.swing.JOptionPane;
import javax.swing.JTabbedPane;
import jhospital.controller.PacienteController;
import jhospital.model.Paciente;


public class CadastroDePacienteView extends javax.swing.JPanel {

    private JTabbedPane tabbedPane;
    private Paciente paciente;

    public CadastroDePacienteView(JTabbedPane tabbedPane1) {
        this.tabbedPane = tabbedPane1;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelCadastroDePaciente = new javax.swing.JLabel();
        SeparatorSuperior = new javax.swing.JSeparator();
        labelNome = new javax.swing.JLabel();
        textFieldNome = new javax.swing.JTextField();
        labelEndereco = new javax.swing.JLabel();
        textFieldEndereco = new javax.swing.JTextField();
        labelEmail = new javax.swing.JLabel();
        textFieldEmail = new javax.swing.JTextField();
        labelTelefone = new javax.swing.JLabel();
        textFieldTelefone = new javax.swing.JTextField();
        labelQuarto = new javax.swing.JLabel();
        textFieldQuarto = new javax.swing.JTextField();
        labelDoenca = new javax.swing.JLabel();
        textFieldDoenca = new javax.swing.JTextField();
        labelPlanoDeSaude = new javax.swing.JLabel();
        textFieldDiasInternado = new javax.swing.JTextField();
        labelDiasInternado = new javax.swing.JLabel();
        comboBoxPlanoDeSaude = new javax.swing.JComboBox();
        buttonSalvar = new javax.swing.JButton();
        buttonCancelar = new javax.swing.JButton();

        labelCadastroDePaciente.setText("Cadastro de Paciente");

        labelNome.setText("Nome Completo:");

        labelEndereco.setText("Endereço:");

        labelEmail.setText("Email:");

        labelTelefone.setText("Telefone:");

        labelQuarto.setText("Quarto:");

        labelDoenca.setText("Doença:");

        labelPlanoDeSaude.setText("Plano de Saúde:");

        labelDiasInternado.setText("Dias Internado");

        comboBoxPlanoDeSaude.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sim", "Não" }));

        buttonSalvar.setText("Salvar");
        buttonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSalvarActionPerformed(evt);
            }
        });

        buttonCancelar.setText("Cancelar");
        buttonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SeparatorSuperior, javax.swing.GroupLayout.DEFAULT_SIZE, 605, Short.MAX_VALUE)
                    .addComponent(labelCadastroDePaciente)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelNome)
                            .addComponent(labelEndereco)
                            .addComponent(labelEmail)
                            .addComponent(labelQuarto)
                            .addComponent(labelDiasInternado))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(textFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                                .addComponent(labelTelefone)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textFieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(textFieldEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE)
                            .addComponent(textFieldNome, javax.swing.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(textFieldQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                                .addComponent(labelDoenca)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textFieldDoenca, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(textFieldDiasInternado, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(buttonSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                                        .addGap(53, 53, 53)
                                        .addComponent(buttonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(labelPlanoDeSaude)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(comboBoxPlanoDeSaude, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelCadastroDePaciente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SeparatorSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNome)
                    .addComponent(textFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEndereco)
                    .addComponent(textFieldEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTelefone)
                    .addComponent(textFieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelEmail)
                    .addComponent(textFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDoenca)
                    .addComponent(textFieldDoenca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelQuarto)
                    .addComponent(textFieldQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPlanoDeSaude)
                    .addComponent(labelDiasInternado)
                    .addComponent(textFieldDiasInternado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxPlanoDeSaude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCancelar)
                    .addComponent(buttonSalvar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void preencherCampos(Integer idPaciente) throws Exception {
        PacienteController pc = new PacienteController();
        paciente = pc.buscarPacientePeloId(idPaciente);
        textFieldNome.setText(paciente.getNome());
        textFieldEmail.setText(paciente.getEmail());
        textFieldEndereco.setText(paciente.getEndereco());
        textFieldTelefone.setText(paciente.getTelefone());
        textFieldQuarto.setText(String
                .valueOf(paciente.getNumerodoquarto()));
        textFieldDoenca.setText(paciente.getDoenca());
        textFieldDiasInternado.setText(String
                .valueOf(paciente.getDiasdeinternacao()));
        if (paciente.getTemplanodesaude()) {
            comboBoxPlanoDeSaude.setSelectedIndex(0);
        } else {
            comboBoxPlanoDeSaude.setSelectedIndex(1);
        }
    }
    
    public CadastroDePacienteView(JTabbedPane tabbedPane1,
            Integer idPaciente) throws Exception {
        this.tabbedPane = tabbedPane1;
        initComponents();
        preencherCampos(idPaciente);
    }
    
private void buttonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelarActionPerformed
    if (JOptionPane.showConfirmDialog(this,
            "Deseja mesmo fechar o cadastro de cliente sem salvar?",
            "Confirmação", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
        tabbedPane.remove(this);
        tabbedPane.validate();
        tabbedPane.repaint();
    }
}//GEN-LAST:event_buttonCancelarActionPerformed

private void buttonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSalvarActionPerformed
    if (textFieldNome != null && !textFieldNome.getText().equals("") &&
            textFieldEmail != null && !textFieldEmail.getText().equals("") &&
            textFieldEndereco != null && !textFieldEndereco.getText().equals("") &&
            textFieldDoenca != null && !textFieldDoenca.getText().equals("")
            ) {
        PacienteController pc = new PacienteController();
        try {
            if (paciente != null && paciente.getId() != null) {
                pc.alterar(paciente.getId(),
                        textFieldNome.getText(),
                        textFieldEmail.getText(),
                        textFieldEndereco.getText(),
                        textFieldTelefone.getText(),
                        textFieldQuarto.getText(),
                        textFieldDoenca.getText(),
                        textFieldDiasInternado.getText(),
                        (String) comboBoxPlanoDeSaude.getSelectedItem());
                JOptionPane.showMessageDialog(this,
                        "Contato atualizado com sucesso!",
                        "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                tabbedPane.remove(this);
                tabbedPane.validate();
                tabbedPane.repaint();
            } else {
            pc.inserir(textFieldNome.getText().toUpperCase(),
                    textFieldEmail.getText().toLowerCase(),
                    textFieldEndereco.getText().toUpperCase(),
                    textFieldTelefone.getText(),
                    textFieldQuarto.getText(),
                    textFieldDoenca.getText().toUpperCase(),
                    textFieldDiasInternado.getText(),
                    (String)comboBoxPlanoDeSaude.getSelectedItem());
            JOptionPane.showMessageDialog(this,
                    "Contato salvo com sucesso!",
                    "Sucesso", JOptionPane.INFORMATION_MESSAGE);
            limparDados();
            }
        }catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Não foi possível salvar contato\n"
                    + e.getLocalizedMessage(),
                    "Erro", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "O nome, email, endereço e doença do paciente são campos obrigatórios!",
                    "Erro", JOptionPane.ERROR_MESSAGE);
    }
}//GEN-LAST:event_buttonSalvarActionPerformed

private void limparDados(){
    textFieldNome.setText("");
    textFieldEmail.setText("");
    textFieldEndereco.setText("");
    textFieldTelefone.setText("");
    textFieldQuarto.setText("");
    textFieldDoenca.setText("");
    textFieldDiasInternado.setText("");
    comboBoxPlanoDeSaude.setSelectedIndex(0);
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator SeparatorSuperior;
    private javax.swing.JButton buttonCancelar;
    private javax.swing.JButton buttonSalvar;
    private javax.swing.JComboBox comboBoxPlanoDeSaude;
    private javax.swing.JLabel labelCadastroDePaciente;
    private javax.swing.JLabel labelDiasInternado;
    private javax.swing.JLabel labelDoenca;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelEndereco;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelPlanoDeSaude;
    private javax.swing.JLabel labelQuarto;
    private javax.swing.JLabel labelTelefone;
    private javax.swing.JTextField textFieldDiasInternado;
    private javax.swing.JTextField textFieldDoenca;
    private javax.swing.JTextField textFieldEmail;
    private javax.swing.JTextField textFieldEndereco;
    private javax.swing.JTextField textFieldNome;
    private javax.swing.JTextField textFieldQuarto;
    private javax.swing.JTextField textFieldTelefone;
    // End of variables declaration//GEN-END:variables
}
