/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ConsultaDeMedicoView.java
 *
 * Created on 21/01/2014, 14:37:23
 */
package jhospital.view.consulta;

import java.awt.Point;
import java.awt.event.MouseEvent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTabbedPane;
import javax.swing.table.DefaultTableModel;
import jhospital.controller.MedicoController;
import jhospital.model.Medico;
import jhospital.view.cadastro.CadastroDeMedicoView;

/**
 *
 * @author GNascimento
 */
public class ConsultaDeMedicoView extends javax.swing.JPanel {

    private JTabbedPane tabbedPane;
    
    public ConsultaDeMedicoView(JTabbedPane tabbedPane1) {
        this.tabbedPane = tabbedPane1;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu = new javax.swing.JPopupMenu();
        menuItemApagar = new javax.swing.JMenuItem();
        menuItemEditar = new javax.swing.JMenuItem();
        labelConsultaDeMedico = new javax.swing.JLabel();
        SeparatorSuperior = new javax.swing.JSeparator();
        labelNome = new javax.swing.JLabel();
        textFieldNome = new javax.swing.JTextField();
        labelEspecialidade = new javax.swing.JLabel();
        textFieldEspecialidade = new javax.swing.JTextField();
        buttonConsultar = new javax.swing.JButton();
        buttonFechar = new javax.swing.JButton();
        ScrollPaneResultados = new javax.swing.JScrollPane();
        tableResultados = new javax.swing.JTable();

        menuItemApagar.setText("Apagar");
        menuItemApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemApagarActionPerformed(evt);
            }
        });
        popupMenu.add(menuItemApagar);

        menuItemEditar.setText("Editar");
        menuItemEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemEditarActionPerformed(evt);
            }
        });
        popupMenu.add(menuItemEditar);

        labelConsultaDeMedico.setText("Consulta de Médico");

        labelNome.setText("Nome:");

        labelEspecialidade.setText("Especialidade:");

        buttonConsultar.setText("Consultar");
        buttonConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonConsultarActionPerformed(evt);
            }
        });

        buttonFechar.setText("Fechar");
        buttonFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFecharActionPerformed(evt);
            }
        });

        tableResultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Endereço", "Email", "Telefone"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableResultados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableResultadosMouseClicked(evt);
            }
        });
        ScrollPaneResultados.setViewportView(tableResultados);
        tableResultados.getColumnModel().getColumn(0).setMinWidth(0);
        tableResultados.getColumnModel().getColumn(0).setPreferredWidth(0);
        tableResultados.getColumnModel().getColumn(0).setMaxWidth(0);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SeparatorSuperior, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ScrollPaneResultados, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(labelConsultaDeMedico)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buttonConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buttonFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(labelEspecialidade)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textFieldEspecialidade, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(labelConsultaDeMedico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SeparatorSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNome)
                    .addComponent(textFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldEspecialidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelEspecialidade))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonFechar)
                    .addComponent(buttonConsultar))
                .addGap(18, 18, 18)
                .addComponent(ScrollPaneResultados, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFecharActionPerformed
        tabbedPane.remove(this);
        tabbedPane.validate();
        tabbedPane.repaint();
    }//GEN-LAST:event_buttonFecharActionPerformed

    private void buttonConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonConsultarActionPerformed
     MedicoController mc = new MedicoController();
        try {
            List<Medico> listaDeMedicos = mc.buscar(
                    textFieldNome.getText(), textFieldEspecialidade.getText());
            DefaultTableModel model = 
                    (DefaultTableModel) tableResultados.getModel();
            for (int i = model.getRowCount() - 1; i >= 0; i--){
                model.removeRow(i);
            }
            if (listaDeMedicos != null) {
                for (int i = 0; i < listaDeMedicos.size(); i++) {
                    Medico medico = listaDeMedicos.get(i);
                    String[] m = new String[] {
                        String.valueOf(medico.getId()),
                        medico.getNome(),
                        medico.getEndereco(),
                        medico.getEmail(),
                        medico.getTelefone()};
                    model.insertRow(i, m);
                    }
                }
                tableResultados.setModel(model);
        }catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Não foi possível consultar os médicos!\n\n"
                    + e.getLocalizedMessage());
            }                       
    }//GEN-LAST:event_buttonConsultarActionPerformed

    private void tableResultadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableResultadosMouseClicked
        try {
            if (evt.getButton() == MouseEvent.BUTTON3) {
                Point p = evt.getPoint();
                int row = tableResultados.rowAtPoint(p);
                if (row >= 0 && row < tableResultados.getRowCount()) {
                    tableResultados
                            .setRowSelectionInterval(row, row);
                    popupMenu.show(evt.getComponent(),
                            evt.getX(), evt.getY());
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Não foi possível abrir o popup!\n\n"
                    + e.getLocalizedMessage());
        }
    }//GEN-LAST:event_tableResultadosMouseClicked

    private void menuItemApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemApagarActionPerformed
        try {
            int row = tableResultados.getSelectedRow();
            MedicoController mc = new MedicoController();
            DefaultTableModel model = (DefaultTableModel) tableResultados
                    .getModel();
            if (JOptionPane.showConfirmDialog(this,
                    "Deseja mesmo apagar o médico " 
                    + model.getValueAt(row, 1).toString(),
                    "Confirmação",
                    JOptionPane.YES_NO_OPTION) ==
                    JOptionPane.YES_OPTION) {
                mc.excluir(Integer.parseInt(model.
                        getValueAt(row, 0).toString()));
                ((DefaultTableModel) tableResultados
                        .getModel()).removeRow(row);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Não foi possível apagar o médico!\n\n"
                    + e.getLocalizedMessage());
        }
    }//GEN-LAST:event_menuItemApagarActionPerformed

    private void menuItemEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemEditarActionPerformed
        try {
            int row = tableResultados.getSelectedRow();
            DefaultTableModel model = 
                    (DefaultTableModel) tableResultados.getModel();
            CadastroDeMedicoView cadastroDeMedicoView;
            cadastroDeMedicoView = new CadastroDeMedicoView(
                    tabbedPane, Integer.parseInt(
                    model.getValueAt(row, 0).toString()));
            tabbedPane.add("Edição de médico",
                    cadastroDeMedicoView);
            tabbedPane.setSelectedComponent(cadastroDeMedicoView);
            tabbedPane.revalidate();
            tabbedPane.repaint();
       } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,
                    "Não é possível editar o médico!\n\n"
                    + ex.getLocalizedMessage());
        }
    }//GEN-LAST:event_menuItemEditarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ScrollPaneResultados;
    private javax.swing.JSeparator SeparatorSuperior;
    private javax.swing.JButton buttonConsultar;
    private javax.swing.JButton buttonFechar;
    private javax.swing.JLabel labelConsultaDeMedico;
    private javax.swing.JLabel labelEspecialidade;
    private javax.swing.JLabel labelNome;
    private javax.swing.JMenuItem menuItemApagar;
    private javax.swing.JMenuItem menuItemEditar;
    private javax.swing.JPopupMenu popupMenu;
    private javax.swing.JTable tableResultados;
    private javax.swing.JTextField textFieldEspecialidade;
    private javax.swing.JTextField textFieldNome;
    // End of variables declaration//GEN-END:variables
}
